# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: terraform-provider-systemd

before:
  hooks:
    - go mod tidy

builds:
  - id: provider
    main: .
    binary: terraform-provider-systemd_v{{ .Version }}
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.Version={{ .Version }}

archives:
  - id: provider
    ids: [provider]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [zip]

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: dlarochette
    name: terraform-provider-systemd
  make_latest: true
